### ISSUE TITLE
Semi colon at and of line causes problems

### ISSUE THREAD

**Issue by markdreyer** [Ravatsaas/the-one-that-aligns-columns#1]
`            ('3016-12-30', '33370076', 'Corporate Cusip 1'  , 'CORPORATES' , 'INDUSTRIAL'     ,  300,  6.0,  2.5, null     ),
            ('3016-12-30', '33370077', 'Corporate Cusip 2'  , 'CORPORATES' , 'INDUSTRIAL'     ,  300, 10.0, null, 999999.00),
            ('3016-12-30', '33370078', 'Corporate Cusip 3'  , 'CORPORATES' , 'INDUSTRIAL'     ,  300, -4.0, -2.5,       -26),
            ('3016-12-30', '33370079', 'Corporate Cusip 4'  , 'CORPORATES' , 'INDUSTRIAL'     ,  300,  5.0, null, null)
            ('3016-12-30', '33370070', 'Corporate Cusip 5'  , 'CORPORATES' , 'INDUSTRIAL'      ,  300,  3.0, null, null    );`

**Comment by Ravatsaas** [comment]
Resolved in release 0.2.0.
