### ISSUE TITLE
Error: Running the contributed command: 'alignColumns.Align' failed.

### ISSUE THREAD

**Issue by markdreyer** [Ravatsaas/the-one-that-aligns-columns#3]
![image](https://user-images.githubusercontent.com/4984469/60197941-1a4d2580-9806-11e9-8efe-953cc3dc09c8.png)

Received error when pressing ALT+, on this data set in blank file:

('07177MAD','BXLT','7/15/2016','7/17/2016'),
('07177MAD','SHPLN','7/18/2016','2/22/2019'),
('07177MAD','TACHEM','2/25/2019','12/31/9999'),
('07177MAG','BXLT','7/15/2016','7/17/2016'),
('07177MAG','SHPLN','7/18/2016','2/22/2019'),
('86765BAT','ETP','5/3/2017','12/31/9999'),
('87425EAJ','TLMCN','10/31/2016','7/17/2017'),
('87425EAJ','REPSM','7/18/2017','12/31/9999')

**Comment by Ravatsaas** [comment]
I am able to reproduce this when the editor has no lines after the text we are aligning. The loop that detects which lines to align needs to take EOF into account.

**Comment by Ravatsaas** [comment]
Fixed in release 0.2.1
