### ISSUE TITLE
When lines are indented, ALT+, Causes lines to indent more each time

### ISSUE THREAD

**Issue by markdreyer** [Ravatsaas/the-one-that-aligns-columns#4]
First of all, LOVE the plugin! It's great. I ran into a little issue today with it handling indented lines. I took a video of the issue. Basically, if you have lines that are indented, pressing ALT + , causes the lines to indent more.

Sample setup:
`

    ,('a', '1', 'z' )
            ,('b', '2', null)
            ,('c', '3', null)
            ,('d', '4', null)

`

Video:

![bug](https://user-images.githubusercontent.com/4984469/63057721-823bf600-beb0-11e9-8ea4-af461af03fbc.gif)

**Comment by Ravatsaas** [comment]
The calculation for how much space to add to the beginning of the line did not take into account the leading comma. (It also currently serves no purpose, but that's another issue altogether (see #2)

Fix is implemented and will be included in the next release.

**Comment by Ravatsaas** [comment]
Fixed in release 0.2.1
